### ISSUE TITLE
Standalone script

### ISSUE THREAD

**Issue by mtravis** [carey136/Standalone-Export-Atlas-QGIS3#2]
This is a good starter for having a stand alone script. It assumes you have installed via osgeo4w I believe. https://gis.stackexchange.com/questions/276902/importing-paths-for-qgis-3-standalone-scripts

**Comment by carey136** [comment]
Thanks @mtravis. The script has been modified to work without launching the QGIS GUI. The README should now include all you need to run the script. In this instance I did need to install using OSGeo4W, and use the following batch file to launch a correctly configured python environment: ``` "C:\OSGeo4W64\bin\python-qgis.bat"  ```
